-- QuizArena – kezdőadatok (seed)
USE quizarena;

-- Szintek
INSERT INTO levels (level_number,xp_required,title) VALUES (1,0,'Újonc');
INSERT INTO levels (level_number,xp_required,title) VALUES (2,100,'Kezdő');
INSERT INTO levels (level_number,xp_required,title) VALUES (3,300,'Haladó');
INSERT INTO levels (level_number,xp_required,title) VALUES (4,600,'Rutinos');
INSERT INTO levels (level_number,xp_required,title) VALUES (5,1000,'Profi');
INSERT INTO levels (level_number,xp_required,title) VALUES (6,1600,'Mester');
INSERT INTO levels (level_number,xp_required,title) VALUES (7,2500,'Kvízmester');

-- Kategóriák
INSERT INTO categories (name,description) VALUES ('Történelem','Magyar és egyetemes történelmi kérdések');
INSERT INTO categories (name,description) VALUES ('Földrajz','Országok, fővárosok, folyók, hegyek');
INSERT INTO categories (name,description) VALUES ('Tudomány','Fizika, kémia, biológia, matematika');
INSERT INTO categories (name,description) VALUES ('Sport','Olimpia, labdarúgás, rekordok');
INSERT INTO categories (name,description) VALUES ('Film és sorozat','Filmek, rendezők, színészek');
INSERT INTO categories (name,description) VALUES ('Zene','Zenetörténet, előadók, hangszerek');
INSERT INTO categories (name,description) VALUES ('Irodalom','Magyar és világirodalom');
INSERT INTO categories (name,description) VALUES ('Technika és informatika','Számítástechnika, találmányok');
INSERT INTO categories (name,description) VALUES ('Művészet','Festészet, építészet, szobrászat');
INSERT INTO categories (name,description) VALUES ('Általános műveltség','Vegyes, mindenféle témából');

-- Felhasználók (a jelszavak SHA-256 hashek; élesben bcrypt ajánlott)
INSERT INTO users (username,email,password_hash,xp,level_id,total_wins,total_games,role) VALUES ('admin','admin@quizarena.hu','240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',2600,7,40,60,'admin');
INSERT INTO users (username,email,password_hash,xp,level_id,total_wins,total_games,role) VALUES ('kvizmester','host@quizarena.hu','0abea6ba7e8d8edb931b17c7add249429d95232502416ec48201f1b0f61ed23c',1200,5,25,45,'host');
INSERT INTO users (username,email,password_hash,xp,level_id,total_wins,total_games,role) VALUES ('jatekos1','anna@example.com','ed20a3f3b8b4c67c848b6f53d9da31270cf3a20998944b2b7e0278dccbb9c18f',350,3,8,20,'player');
INSERT INTO users (username,email,password_hash,xp,level_id,total_wins,total_games,role) VALUES ('jatekos2','bela@example.com','598dbeb7ca96ccc4523ea8c997fc9cbd6be29baf571495ded2788fa71e8455e0',120,2,3,12,'player');
INSERT INTO users (username,email,password_hash,xp,level_id,total_wins,total_games,role) VALUES ('ujonc','cili@example.com','19f18324dfa42ec28807f6c031c9cb24c3883959e13deaa973b1fac04bc2cafb',30,1,0,4,'player');

-- Kérdések és válaszok
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (1,'easy','Melyik évben alapították a Magyar Államot Szent István koronázásával?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (1,'1000',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (1,'1241',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (1,'1526',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (1,'896',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (1,'easy','Ki volt az első magyar király?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (2,'Szent István',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (2,'Szent László',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (2,'Könyves Kálmán',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (2,'Álmos',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (1,'easy','Melyik évben tört ki az 1848–49-es magyar forradalom?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (3,'1848',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (3,'1789',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (3,'1914',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (3,'1956',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (1,'medium','Melyik csatában szenvedett vereséget a magyar sereg 1526-ban?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (4,'Mohácsi csata',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (4,'Muhi csata',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (4,'Nándorfehérvári ostrom',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (4,'Pozsonyi csata',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (1,'medium','Ki volt a Magyar Köztársaság első elnöke 1946-ban?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (5,'Tildy Zoltán',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (5,'Nagy Imre',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (5,'Kádár János',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (5,'Horthy Miklós',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (1,'medium','Melyik évben zajlott a tatárjárás Magyarországon?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (6,'1241',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (6,'1301',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (6,'1456',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (6,'1000',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (1,'hard','Melyik békeszerződés zárta le Magyarország számára az első világháborút?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (7,'Trianoni békeszerződés',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (7,'Párizsi béke',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (7,'Versailles-i béke',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (7,'Westfáliai béke',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (1,'hard','Ki vezette a Rákóczi-szabadságharcot 1703 és 1711 között?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (8,'II. Rákóczi Ferenc',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (8,'Bocskai István',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (8,'Thököly Imre',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (8,'Bethlen Gábor',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (1,'hard','Melyik évben esett el Buda a török ostrom során, majd lett vissza 1686-ban?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (9,'1541',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (9,'1526',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (9,'1699',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (9,'1568',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (2,'easy','Mi Magyarország fővárosa?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (10,'Budapest',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (10,'Debrecen',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (10,'Szeged',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (10,'Győr',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (2,'easy','Melyik a leghosszabb folyó Magyarországon?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (11,'Tisza',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (11,'Duna',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (11,'Dráva',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (11,'Rába',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (2,'easy','Melyik kontinensen található Egyiptom?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (12,'Afrika',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (12,'Ázsia',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (12,'Európa',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (12,'Dél-Amerika',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (2,'medium','Mi Ausztrália fővárosa?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (13,'Canberra',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (13,'Sydney',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (13,'Melbourne',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (13,'Perth',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (2,'medium','Melyik a Föld legnagyobb óceánja?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (14,'Csendes-óceán',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (14,'Atlanti-óceán',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (14,'Indiai-óceán',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (14,'Jeges-tenger',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (2,'medium','Melyik ország fővárosa Ottawa?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (15,'Kanada',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (15,'Ausztrália',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (15,'Új-Zéland',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (15,'USA',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (2,'hard','Melyik a világ legmagasabb hegycsúcsa?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (16,'Mount Everest',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (16,'K2',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (16,'Kilimandzsáró',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (16,'Mont Blanc',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (2,'hard','Melyik ország területe a legnagyobb a világon?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (17,'Oroszország',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (17,'Kanada',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (17,'Kína',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (17,'USA',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (2,'hard','Melyik afrikai ország fővárosa Nairobi?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (18,'Kenya',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (18,'Tanzánia',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (18,'Uganda',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (18,'Etiópia',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (3,'easy','Mi a víz kémiai képlete?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (19,'H2O',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (19,'CO2',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (19,'O2',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (19,'NaCl',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (3,'easy','Hány lába van egy rovarnak?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (20,'6',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (20,'8',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (20,'4',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (20,'10',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (3,'easy','Melyik bolygó van legközelebb a Naphoz?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (21,'Merkúr',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (21,'Vénusz',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (21,'Föld',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (21,'Mars',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (3,'medium','Mi az emberi test legnagyobb szerve?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (22,'A bőr',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (22,'A máj',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (22,'A tüdő',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (22,'A szív',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (3,'medium','Melyik gáz teszi ki a Föld légkörének legnagyobb részét?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (23,'Nitrogén',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (23,'Oxigén',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (23,'Szén-dioxid',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (23,'Hidrogén',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (3,'medium','Ki dolgozta ki a relativitáselméletet?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (24,'Albert Einstein',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (24,'Isaac Newton',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (24,'Nikola Tesla',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (24,'Galilei',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (3,'hard','Mi a fénysebesség vákuumban közelítőleg?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (25,'300 000 km/s',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (25,'150 000 km/s',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (25,'1 000 km/s',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (25,'30 000 km/s',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (3,'hard','Melyik kémiai elem vegyjele az ''Au''?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (26,'Arany',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (26,'Ezüst',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (26,'Alumínium',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (26,'Argon',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (3,'hard','Hány kromoszómája van egy egészséges embernek?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (27,'46',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (27,'23',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (27,'48',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (27,'44',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (4,'easy','Hány játékos van egy focicsapatban a pályán egyszerre?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (28,'11',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (28,'9',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (28,'7',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (28,'13',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (4,'easy','Melyik sportághoz kötődik a Wimbledon?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (29,'Tenisz',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (29,'Golf',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (29,'Krikett',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (29,'Úszás',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (4,'easy','Milyen színű a szumó küzdőtér határvonala hagyományosan?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (30,'Fehér',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (30,'Piros',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (30,'Fekete',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (30,'Kék',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (4,'medium','Hány évente rendezik a nyári olimpiai játékokat?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (31,'4 évente',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (31,'2 évente',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (31,'3 évente',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (31,'5 évente',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (4,'medium','Melyik országból származik a judo sportág?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (32,'Japán',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (32,'Kína',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (32,'Korea',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (32,'Thaiföld',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (4,'medium','Ki nyerte a legtöbb Forma-1 világbajnoki címet (7-tel megosztva)?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (33,'Lewis Hamilton',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (33,'Ayrton Senna',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (33,'Niki Lauda',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (33,'Sebastian Vettel',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (4,'hard','Melyik évben rendeztek először modern kori olimpiát?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (34,'1896',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (34,'1900',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (34,'1924',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (34,'1888',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (4,'hard','Hány gyűrű látható az olimpiai zászlón?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (35,'5',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (35,'4',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (35,'6',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (35,'3',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (4,'hard','Melyik magyar úszó nyert három aranyérmet a 2016-os riói olimpián?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (36,'Hosszú Katinka',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (36,'Cseh László',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (36,'Gyurta Dániel',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (36,'Kapás Boglárka',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (5,'easy','Melyik animációs stúdió készítette az Oroszlánkirályt?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (37,'Disney',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (37,'Pixar',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (37,'DreamWorks',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (37,'Studio Ghibli',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (5,'easy','Ki játssza a Vasembert a Marvel-filmekben?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (38,'Robert Downey Jr.',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (38,'Chris Evans',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (38,'Chris Hemsworth',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (38,'Mark Ruffalo',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (5,'medium','Ki rendezte a Titanic című filmet?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (39,'James Cameron',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (39,'Steven Spielberg',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (39,'Christopher Nolan',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (39,'Ridley Scott',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (5,'medium','Melyik filmben hangzik el a ''Az erő legyen veled!'' mondat?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (40,'Csillagok háborúja',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (40,'Star Trek',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (40,'Alien',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (40,'Blade Runner',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (5,'medium','Melyik sorozat játszódik Westeros kontinensén?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (41,'Trónok harca',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (41,'The Witcher',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (41,'Vikingek',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (41,'Rómaiak',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (5,'hard','Melyik film nyerte el a legjobb film Oscar-díját 2020-ban?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (42,'Élősködők (Parasite)',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (42,'1917',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (42,'Joker',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (42,'Volt egyszer egy Hollywood',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (5,'hard','Ki rendezte az Eredet (Inception) című filmet?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (43,'Christopher Nolan',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (43,'Denis Villeneuve',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (43,'David Fincher',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (43,'Quentin Tarantino',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (6,'easy','Hány húrja van egy hagyományos gitárnak?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (44,'6',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (44,'4',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (44,'5',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (44,'7',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (6,'easy','Melyik együttes adta ki a ''Bohemian Rhapsody'' című dalt?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (45,'Queen',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (45,'The Beatles',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (45,'Rolling Stones',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (45,'Pink Floyd',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (6,'medium','Ki komponálta a ''Kilencedik szimfóniát'' (Örömóda)?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (46,'Beethoven',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (46,'Mozart',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (46,'Bach',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (46,'Chopin',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (6,'medium','Melyik hangszer tartozik a fúvós hangszerek közé?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (47,'Trombita',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (47,'Hegedű',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (47,'Zongora',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (47,'Dob',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (6,'medium','Melyik magyar zeneszerző írta a ''Háry János'' című daljátékot?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (48,'Kodály Zoltán',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (48,'Bartók Béla',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (48,'Liszt Ferenc',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (48,'Erkel Ferenc',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (6,'hard','Hány billentyű van egy standard zongorán?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (49,'88',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (49,'76',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (49,'61',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (49,'102',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (6,'hard','Ki szerezte a magyar Himnusz zenéjét?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (50,'Erkel Ferenc',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (50,'Kölcsey Ferenc',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (50,'Liszt Ferenc',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (50,'Egressy Béni',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (7,'easy','Ki írta a ''János vitéz'' című elbeszélő költeményt?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (51,'Petőfi Sándor',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (51,'Arany János',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (51,'Ady Endre',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (51,'József Attila',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (7,'easy','Ki írta a ''Rómeó és Júlia'' című drámát?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (52,'William Shakespeare',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (52,'Molière',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (52,'Goethe',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (52,'Dante',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (7,'medium','Ki írta az ''Egri csillagok'' című regényt?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (53,'Gárdonyi Géza',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (53,'Jókai Mór',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (53,'Mikszáth Kálmán',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (53,'Móricz Zsigmond',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (7,'medium','Melyik magyar költő írta a ''Nemzeti dal'' című verset?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (54,'Petőfi Sándor',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (54,'Arany János',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (54,'Vörösmarty Mihály',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (54,'Ady Endre',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (7,'medium','Ki a szerzője a ''Bűn és bűnhődés'' című regénynek?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (55,'Dosztojevszkij',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (55,'Tolsztoj',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (55,'Csehov',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (55,'Puskin',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (7,'hard','Melyik évben kapott Kertész Imre irodalmi Nobel-díjat?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (56,'2002',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (56,'1996',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (56,'2010',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (56,'1988',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (7,'hard','Ki írta ''Az ember tragédiája'' című drámai költeményt?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (57,'Madách Imre',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (57,'Vörösmarty Mihály',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (57,'Katona József',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (57,'Arany János',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (8,'easy','Mit jelent a ''CPU'' rövidítés?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (58,'Központi feldolgozó egység',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (58,'Számítógépes tápegység',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (58,'Grafikus kártya',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (58,'Merevlemez',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (8,'easy','Melyik cég fejlesztette a Windows operációs rendszert?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (59,'Microsoft',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (59,'Apple',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (59,'Google',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (59,'IBM',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (8,'easy','Hány bit egy bájt?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (60,'8',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (60,'4',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (60,'16',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (60,'32',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (8,'medium','Mit jelent a ''HTML'' rövidítés?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (61,'HyperText Markup Language',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (61,'High Tech Modern Language',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (61,'Home Tool Markup Language',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (61,'Hyperlink Text Mode Language',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (8,'medium','Ki alapította a Microsoftot Paul Allennel együtt?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (62,'Bill Gates',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (62,'Steve Jobs',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (62,'Mark Zuckerberg',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (62,'Larry Page',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (8,'medium','Melyik programozási nyelv logója egy kávéscsésze?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (63,'Java',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (63,'Python',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (63,'C++',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (63,'Ruby',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (8,'hard','Melyik évben mutatták be az első iPhone-t?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (64,'2007',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (64,'2005',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (64,'2010',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (64,'2003',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (8,'hard','Mit jelent az ''SQL'' rövidítés?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (65,'Structured Query Language',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (65,'Simple Question Language',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (65,'System Query Logic',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (65,'Standard Quality Level',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (8,'hard','Melyik adatszerkezet működik a LIFO (utoljára be, először ki) elv szerint?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (66,'Verem (stack)',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (66,'Sor (queue)',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (66,'Láncolt lista',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (66,'Fa',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (9,'easy','Ki festette a Mona Lisát?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (67,'Leonardo da Vinci',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (67,'Michelangelo',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (67,'Raffaello',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (67,'Van Gogh',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (9,'easy','Melyik művész vágta le a saját fülét?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (68,'Vincent van Gogh',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (68,'Pablo Picasso',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (68,'Claude Monet',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (68,'Salvador Dalí',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (9,'medium','Melyik stílusirányzat fő képviselője Salvador Dalí?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (69,'Szürrealizmus',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (69,'Impresszionizmus',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (69,'Kubizmus',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (69,'Reneszánsz',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (9,'medium','Ki tervezte a barcelonai Sagrada Família templomot?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (70,'Antoni Gaudí',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (70,'Le Corbusier',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (70,'Frank Lloyd Wright',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (70,'Gustave Eiffel',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (9,'hard','Melyik városban található a Louvre múzeum?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (71,'Párizs',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (71,'London',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (71,'Madrid',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (71,'Róma',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (9,'hard','Ki festette a ''Csillagos éj'' című képet?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (72,'Vincent van Gogh',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (72,'Claude Monet',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (72,'Edvard Munch',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (72,'Gustav Klimt',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (10,'easy','Hány napból áll egy szökőév?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (73,'366',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (73,'365',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (73,'364',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (73,'367',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (10,'easy','Milyen színt kapunk, ha a kéket és a sárgát összekeverjük?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (74,'Zöld',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (74,'Lila',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (74,'Narancs',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (74,'Barna',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (10,'easy','Hány óra van egy napban?',10,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (75,'24',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (75,'12',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (75,'48',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (75,'36',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (10,'medium','Melyik pénznemet használják Japánban?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (76,'Jen',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (76,'Won',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (76,'Jüan',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (76,'Bát',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (10,'medium','Hány kontinens van a Földön?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (77,'7',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (77,'5',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (77,'6',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (77,'8',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (10,'medium','Melyik vitaminból jutunk sokhoz napfény hatására?',20,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (78,'D-vitamin',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (78,'C-vitamin',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (78,'B12-vitamin',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (78,'A-vitamin',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (10,'hard','Hány elem található a periódusos rendszerben (2024-es állapot szerint kb.)?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (79,'118',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (79,'108',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (79,'120',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (79,'98',FALSE);
INSERT INTO questions (category_id,difficulty,question_text,points,created_by,is_public) VALUES (10,'hard','Melyik évben lépett le először ember a Holdra?',30,1,TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (80,'1969',TRUE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (80,'1972',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (80,'1961',FALSE);
INSERT INTO answers (question_id,answer_text,is_correct) VALUES (80,'1975',FALSE);

-- Kvízek
INSERT INTO quizzes (title,description,created_by,mode,is_public) VALUES ('Vegyes tudáspróba','Minden témából egy kis ízelítő',1,'classic',TRUE);
INSERT INTO quizzes (title,description,created_by,mode,is_public) VALUES ('Villámkör – időre','Gyors kérdések visszaszámlálóval',2,'timed',TRUE);
INSERT INTO quizzes (title,description,created_by,mode,is_public) VALUES ('Milliomos kihívás','Fokozódó nehézségű kérdéssor',2,'millionaire',TRUE);
INSERT INTO quizzes (title,description,created_by,mode,is_public) VALUES ('Történelem mesterkör','Csak a bátraknak, nehéz kérdésekkel',1,'classic',TRUE);

-- Kvízekhez rendelt kérdések
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (1,1,1);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (1,10,2);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (1,19,3);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (1,28,4);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (1,37,5);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (1,44,6);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (1,51,7);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (1,58,8);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (1,67,9);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (1,73,10);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (2,1,1);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (2,2,2);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (2,3,3);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (2,10,4);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (2,11,5);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (2,12,6);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (2,19,7);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (2,20,8);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (3,1,1);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (3,2,2);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (3,3,3);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (3,4,4);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (3,5,5);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (3,6,6);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (3,7,7);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (3,8,8);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (3,9,9);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (4,7,1);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (4,8,2);
INSERT INTO quiz_questions (quiz_id,question_id,position) VALUES (4,9,3);

-- Minta eredmények
INSERT INTO results (user_id,quiz_id,score,correct_count,time_spent) VALUES (3,1,70,8,95);
INSERT INTO results (user_id,quiz_id,score,correct_count,time_spent) VALUES (4,1,50,6,120);
INSERT INTO results (user_id,quiz_id,score,correct_count,time_spent) VALUES (3,2,60,7,45);
INSERT INTO results (user_id,quiz_id,score,correct_count,time_spent) VALUES (5,1,30,4,150);
